PACKAGE_NAME="rtl8821ce"
PACKAGE_VERSION="#MODULE_VERSION#"
BUILT_MODULE_NAME[0]="8821ce"
MAKE="'make' -j$(nproc) KVER=$kernelver CC=$(if grep -q CONFIG_CC_IS_CLANG=y /lib/modules/$kernelver/build/.config 2>/dev/null; then echo clang; else echo gcc; fi) LLVM=$(if grep -q CONFIG_CC_IS_CLANG=y /lib/modules/$kernelver/build/.config 2>/dev/null; then echo 1; else echo 0; fi)"
CLEAN="'make' clean"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="YES"
